default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: mysql

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test
